export const SECRET_KEY = "AgsqyqyY(bu7*7^2…7[bu&x#a@es729100qiYe29Bw3";

export const achievementsList = [
  { key: "first-game", icon: "🐣", condition: (state) => state.games.gte(1) },
  { key: "100-game", icon: "💰", condition: (state) => state.games.gte(100) },
  { key: "1000-game", icon: "💰", condition: (state) => state.games.gte(1000) },
  {
    key: "10000-game",
    icon: "🚀",
    condition: (state) => state.games.gte(10000),
  },
  {
    key: "100000-game",
    icon: "🛰️",
    condition: (state) => state.games.gte(100000),
  },
  {
    key: "1000000-game",
    icon: "🌌",
    condition: (state) => state.games.gte(1000000),
  },
  {
    key: "10000000-game",
    icon: "☄️",
    condition: (state) => state.games.gte(10000000),
  },
  {
    key: "100000000-game",
    icon: "🛸",
    condition: (state) => state.games.gte(100000000),
  },
  {
    key: "1000000000-game",
    icon: "🔭",
    condition: (state) => state.games.gte(1000000000),
  },
  {
    key: "10000000000-game",
    icon: "🌌",
    condition: (state) => state.games.gte(10000000000),
  },
  {
    key: "100000000000-game",
    icon: "🌠",
    condition: (state) => state.games.gte(100000000000),
  },
  { key: "1e12-game", icon: "🛰️", condition: (state) => state.games.gte(1e12) },
  { key: "1e13-game", icon: "🚀", condition: (state) => state.games.gte(1e13) },
  { key: "1e14-game", icon: "🛸", condition: (state) => state.games.gte(1e14) },
  { key: "1e15-game", icon: "🛸", condition: (state) => state.games.gte(1e15) },
  { key: "1e16-game", icon: "☄️", condition: (state) => state.games.gte(1e16) },
  { key: "1e17-game", icon: "🌀", condition: (state) => state.games.gte(1e17) },
  { key: "1e18-game", icon: "💎", condition: (state) => state.games.gte(1e18) },
  { key: "1e19-game", icon: "✨", condition: (state) => state.games.gte(1e19) },
  { key: "1e20-game", icon: "♾️", condition: (state) => state.games.gte(1e20) },
  { key: "1e21-game", icon: "🎇", condition: (state) => state.games.gte(1e21) },
  { key: "1e22-game", icon: "🎆", condition: (state) => state.games.gte(1e22) },
  { key: "1e24-game", icon: "🌈", condition: (state) => state.games.gte(1e24) },
  { key: "1e27-game", icon: "☀️", condition: (state) => state.games.gte(1e27) },
  { key: "1e30-game", icon: "🌟", condition: (state) => state.games.gte(1e30) },
  { key: "1e35-game", icon: "🔮", condition: (state) => state.games.gte(1e35) },
  { key: "1e40-game", icon: "🧿", condition: (state) => state.games.gte(1e40) },
  { key: "1e50-game", icon: "👑", condition: (state) => state.games.gte(1e50) },
  { key: "1e60-game", icon: "🔱", condition: (state) => state.games.gte(1e60) },
  {
    key: "1e100-game",
    icon: "💯",
    condition: (state) => state.games.gte(1e100),
  },
  { key: "100-money", icon: "💰", condition: (state) => state.money.gt(100) },
  {
    key: "1000-money",
    icon: "💵",
    condition: (state) => state.money.gte(1000),
  },
  {
    key: "100000-money",
    icon: "💎",
    condition: (state) => state.money.gte(100000),
  },
  {
    key: "1000000-money",
    icon: "🏦",
    condition: (state) => state.money.gte(1000000),
  },
  {
    key: "10000000-money",
    icon: "🏛️",
    condition: (state) => state.money.gte(10000000),
  },
  {
    key: "100000000-money",
    icon: "💰",
    condition: (state) => state.money.gte(100000000),
  },
  {
    key: "many-money",
    icon: "💵",
    condition: (state) => state.money.gte(1000000000),
  },
  {
    key: "10000000000-money",
    icon: "💎",
    condition: (state) => state.money.gte(10000000000),
  },
  {
    key: "100000000000-money",
    icon: "🏦",
    condition: (state) => state.money.gte(100000000000),
  },
  {
    key: "1000000000000-money",
    icon: "🏛️",
    condition: (state) => state.money.gte(1000000000000),
  },
  {
    key: "1000000000000000-money",
    icon: "💰",
    condition: (state) => state.money.gte(1000000000000000),
  },
  {
    key: "1e16-money",
    icon: "💵",
    condition: (state) => state.money.gte(1e16),
  },
  {
    key: "1e17-money",
    icon: "💎",
    condition: (state) => state.money.gte(1e17),
  },
  {
    key: "1e18-money",
    icon: "🏦",
    condition: (state) => state.money.gte(1e18),
  },
  {
    key: "1e19-money",
    icon: "🏛️",
    condition: (state) => state.money.gte(1e19),
  },
  {
    key: "1e20-money",
    icon: "💰",
    condition: (state) => state.money.gte(1e20),
  },
  {
    key: "1e21-money",
    icon: "💵",
    condition: (state) => state.money.gte(1e21),
  },
  {
    key: "1e22-money",
    icon: "💎",
    condition: (state) => state.money.gte(1e22),
  },
  {
    key: "1e23-money",
    icon: "🏦",
    condition: (state) => state.money.gte(1e23),
  },
  {
    key: "1e24-money",
    icon: "🏛️",
    condition: (state) => state.money.gte(1e24),
  },
  {
    key: "1e25-money",
    icon: "💰",
    condition: (state) => state.money.gte(1e25),
  },
  {
    key: "1e26-money",
    icon: "💵",
    condition: (state) => state.money.gte(1e26),
  },
  {
    key: "1e27-money",
    icon: "💎",
    condition: (state) => state.money.gte(1e27),
  },
  {
    key: "1e28-money",
    icon: "🏦",
    condition: (state) => state.money.gte(1e28),
  },
  {
    key: "1e30-money",
    icon: "🏛️",
    condition: (state) => state.money.gte(1e30),
  },
  {
    key: "1e33-money",
    icon: "💰",
    condition: (state) => state.money.gte(1e33),
  },
  {
    key: "1e36-money",
    icon: "💵",
    condition: (state) => state.money.gte(1e36),
  },
  {
    key: "1e40-money",
    icon: "💎",
    condition: (state) => state.money.gte(1e40),
  },
  {
    key: "1e45-money",
    icon: "🏦",
    condition: (state) => state.money.gte(1e45),
  },
  {
    key: "1e50-money",
    icon: "🏛️",
    condition: (state) => state.money.gte(1e50),
  },
  {
    key: "1e60-money",
    icon: "💰",
    condition: (state) => state.money.gte(1e60),
  },
  {
    key: "1e70-money",
    icon: "💵",
    condition: (state) => state.money.gte(1e70),
  },
  {
    key: "1e80-money",
    icon: "💎",
    condition: (state) => state.money.gte(1e80),
  },
  {
    key: "1e90-money",
    icon: "🏦",
    condition: (state) => state.money.gte(1e90),
  },
  {
    key: "1e100-money",
    icon: "🏛️",
    condition: (state) => state.money.gte(1e100),
  },
  {
    key: "1e120-money",
    icon: "💰",
    condition: (state) => state.money.gte(1e120),
  },
  {
    key: "1e150-money",
    icon: "💵",
    condition: (state) => state.money.gte(1e150),
  },
  { key: "1-developer", icon: "🤝", condition: (state) => state.developer >= 1 },
  {
    key: "10-developer",
    icon: "👥",
    condition: (state) => state.developer >= 10,
  },
  {
    key: "50-developer",
    icon: "🏢",
    condition: (state) => state.developer >= 50,
  },
  {
    key: "100-developer",
    icon: "🏢",
    condition: (state) => state.developer >= 100,
  },
  {
    key: "250-developer",
    icon: "🏙️",
    condition: (state) => state.developer >= 250,
  },
  {
    key: "500-developer",
    icon: "🏙️",
    condition: (state) => state.developer >= 500,
  },
  {
    key: "1000-developer",
    icon: "🌍",
    condition: (state) => state.developer >= 1000,
  },
  {
    key: "2500-developer",
    icon: "🗺️",
    condition: (state) => state.developer >= 2500,
  },
  {
    key: "5000-developer",
    icon: "🌐",
    condition: (state) => state.developer >= 5000,
  },
  {
    key: "10000-developer",
    icon: "🪐",
    condition: (state) => state.developer >= 10000,
  },
  {
    key: "25000-developer",
    icon: "🧑‍💻",
    condition: (state) => state.developer >= 25000,
  },
  {
    key: "50000-developer",
    icon: "👨‍💻",
    condition: (state) => state.developer >= 50000,
  },
  {
    key: "100000-developer",
    icon: "👩‍💻",
    condition: (state) => state.developer >= 100000,
  },
  {
    key: "250000-developer",
    icon: "🧑‍💼",
    condition: (state) => state.developer >= 250000,
  },
  {
    key: "500000-developer",
    icon: "👨‍💼",
    condition: (state) => state.developer >= 500000,
  },
  {
    key: "1000000-developer",
    icon: "👩‍💼",
    condition: (state) => state.developer >= 1000000,
  },
  {
    key: "10000000-developer",
    icon: "🧑‍🔬",
    condition: (state) => state.developer >= 10000000,
  },
  { key: "1-company", icon: "💼", condition: (state) => state.company >= 1 },
  { key: "10-company", icon: "🏪", condition: (state) => state.company >= 10 },
  {
    key: "100-company",
    icon: "🏭",
    condition: (state) => state.company >= 100,
  },
  {
    key: "1000-company",
    icon: "🏙️",
    condition: (state) => state.company >= 1000,
  },
  {
    key: "2500-company",
    icon: "🏢",
    condition: (state) => state.company >= 2500,
  },
  {
    key: "5000-company",
    icon: "🏙️",
    condition: (state) => state.company >= 5000,
  },
  {
    key: "10000-company",
    icon: "🌃",
    condition: (state) => state.company >= 10000,
  },
  {
    key: "25000-company",
    icon: "🌆",
    condition: (state) => state.company >= 25000,
  },
  {
    key: "50000-company",
    icon: "🛰️",
    condition: (state) => state.company >= 50000,
  },
  {
    key: "100000-company",
    icon: "🌌",
    condition: (state) => state.company >= 100000,
  },
  {
    key: "250000-company",
    icon: "🌃",
    condition: (state) => state.company >= 250000,
  },
  {
    key: "500000-company",
    icon: "🏙️",
    condition: (state) => state.company >= 500000,
  },
  {
    key: "1000000-company",
    icon: "🌍",
    condition: (state) => state.company >= 1000000,
  },
  {
    key: "5000000-company",
    icon: "🌐",
    condition: (state) => state.company >= 5000000,
  },
  {
    key: "10000000-company",
    icon: "🪐",
    condition: (state) => state.company >= 10000000,
  },
  {
    key: "100000000-company",
    icon: "🌌",
    condition: (state) => state.company >= 100000000,
  },
  {
    key: "1000000000-company",
    icon: "🌀",
    condition: (state) => state.company >= 1000000000,
  },
  {
    key: "first-upgrade",
    icon: "🆙",
    condition: (state) => state.currentCompanyGrade >= 2,
  },
  {
    key: "5-grade",
    icon: "🏢",
    condition: (state) => state.currentCompanyGrade >= 5,
  },
  {
    key: "10-grade",
    icon: "⭐",
    condition: (state) => state.currentCompanyGrade >= 10,
  },
  {
    key: "last-upgrade",
    icon: "🎖️",
    condition: (state) => state.currentCompanyGrade >= 15,
  },
  {
    key: "20-grade",
    icon: "🏅",
    condition: (state) => state.currentCompanyGrade >= 20,
  },
  {
    key: "25-grade",
    icon: "🥇",
    condition: (state) => state.currentCompanyGrade >= 25,
  },
  {
    key: "30-grade",
    icon: "💎",
    condition: (state) => state.currentCompanyGrade >= 30,
  },
  {
    key: "40-grade",
    icon: "👑",
    condition: (state) => state.currentCompanyGrade >= 40,
  },
  {
    key: "50-grade",
    icon: "🌟",
    condition: (state) => state.currentCompanyGrade >= 50,
  },
  {
    key: "75-grade",
    icon: "🔥",
    condition: (state) => state.currentCompanyGrade >= 75,
  },
  {
    key: "100-grade",
    icon: "💯",
    condition: (state) => state.currentCompanyGrade >= 100,
  },
  { key: "ai-unlocked", icon: "⚡", condition: (state) => state.aiEnabled },
  {
    key: "1-ai-dev",
    icon: "🤖",
    condition: (state) => (state.aiDev || 0) >= 1,
  },
  {
    key: "10-ai-dev",
    icon: "🌐",
    condition: (state) => (state.aiDev || 0) >= 10,
  },
  {
    key: "50-ai-dev",
    icon: "🧠",
    condition: (state) => (state.aiDev || 0) >= 50,
  },
  {
    key: "100-ai-dev",
    icon: "🧬",
    condition: (state) => (state.aiDev || 0) >= 100,
  },
  {
    key: "250-ai-dev",
    icon: "🕸️",
    condition: (state) => (state.aiDev || 0) >= 250,
  },
  {
    key: "500-ai-dev",
    icon: "💠",
    condition: (state) => (state.aiDev || 0) >= 500,
  },
  {
    key: "1000-ai-dev",
    icon: "📡",
    condition: (state) => (state.aiDev || 0) >= 1000,
  },
  {
    key: "2500-ai-dev",
    icon: "🛰️",
    condition: (state) => (state.aiDev || 0) >= 2500,
  },
  {
    key: "5000-ai-dev",
    icon: "🌌",
    condition: (state) => (state.aiDev || 0) >= 5000,
  },
  {
    key: "10000-ai-dev",
    icon: "📡",
    condition: (state) => (state.aiDev || 0) >= 10000,
  },
  {
    key: "25000-ai-dev",
    icon: "🛰️",
    condition: (state) => (state.aiDev || 0) >= 25000,
  },
  {
    key: "50000-ai-dev",
    icon: "🌌",
    condition: (state) => (state.aiDev || 0) >= 50000,
  },
  {
    key: "100000-ai-dev",
    icon: "🌀",
    condition: (state) => (state.aiDev || 0) >= 100000,
  },
  {
    key: "250000-ai-dev",
    icon: "⚛️",
    condition: (state) => (state.aiDev || 0) >= 250000,
  },
  {
    key: "500000-ai-dev",
    icon: "🧿",
    condition: (state) => (state.aiDev || 0) >= 500000,
  },
  {
    key: "1000000-ai-dev",
    icon: "🧬",
    condition: (state) => (state.aiDev || 0) >= 1000000,
  },
  {
    key: "2500000-ai-dev",
    icon: "🦾",
    condition: (state) => (state.aiDev || 0) >= 2500000,
  },
  {
    key: "5000000-ai-dev",
    icon: "🦿",
    condition: (state) => (state.aiDev || 0) >= 5000000,
  },
  {
    key: "10000000-ai-dev",
    icon: "🖥️",
    condition: (state) => (state.aiDev || 0) >= 10000000,
  },
  {
    key: "25000000-ai-dev",
    icon: "💻",
    condition: (state) => (state.aiDev || 0) >= 25000000,
  },
  {
    key: "50000000-ai-dev",
    icon: "⌨️",
    condition: (state) => (state.aiDev || 0) >= 50000000,
  },
  {
    key: "100000000-ai-dev",
    icon: "🖱️",
    condition: (state) => (state.aiDev || 0) >= 100000000,
  },
  {
    key: "500000000-ai-dev",
    icon: "🖲️",
    condition: (state) => (state.aiDev || 0) >= 500000000,
  },
  {
    key: "1000000000-ai-dev",
    icon: "🕹️",
    condition: (state) => (state.aiDev || 0) >= 1000000000,
  },
  {
    key: "international",
    icon: "🌍",
    condition: (state) => (state.usedLanguages || []).length >= 5,
  },
  {
    key: "billing-received",
    icon: "💸",
    condition: (state) => (state.billingCount || 0) >= 1,
  },
  {
    key: "10-billing",
    icon: "💸",
    condition: (state) => (state.billingCount || 0) >= 10,
  },
  {
    key: "100-billing",
    icon: "💵",
    condition: (state) => (state.billingCount || 0) >= 100,
  },
  {
    key: "1000-billing",
    icon: "💰",
    condition: (state) => (state.billingCount || 0) >= 1000,
  },
  {
    key: "10000-billing",
    icon: "💎",
    condition: (state) => (state.billingCount || 0) >= 10000,
  },
];
